movie_app/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", views.register, name="register"),
    path('', include('movies.urls')),
    path('login/', LoginView.as_view(template_name="users/login.html")),
    path('', include('django.contrib.auth.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list_movies, name='list_movies'),
    path('lookup', views.lookup, name='lookup'),
    path('add', views.add, name='add'),
    path('add_to_plex', views.add_plex, name='add_plex'),
    path('download', views.list_to_download, name="list_to_download"),
    path('download/add', views.create_torrent_download, name="create_torrent_download"),
    path('torrents/1337x', views.list_create_1337x_torrents, name="list_1337x"),
]

urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('lookup', views.lookup, name='lookup'),
    path('add', views.add, name='add'),
    path('add_to_plex', views.add_plex, name='add_plex')
]

movies/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

class Providers(models.Model):
    name = models.CharField(max_length=255, unique=True)
    logo = models.URLField()

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']

class Media(models.Model):
    # TODO: Move genre relationship to genre model with a onetomany to media
    imdbID = models.CharField(max_length=100, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    year = models.CharField(max_length=4)
    rated = models.CharField(max_length=5)
    runtime = models.CharField(max_length=10)
    genre = models.ManyToManyField(Genre)
    director = models.CharField(max_length=255)
    actors = models.CharField(max_length=255)
    plot = models.TextField()
    poster = models.URLField()
    rating = models.CharField(max_length=10)
    media_type = models.CharField(max_length=30)
    providers = models.ManyToManyField(Providers)

    def __str__(self):
        return f"{self.title} - {self.year}"

    class Meta:
        ordering = ['title']
        
class Torrents(models.Model):
    status_choices = (
        ("COMPLETE", "complete"),
        ("IN-PROGRESS", "in-progress"),
        ("READY", "ready"),
    )
    magnet = models.URLField()
    status = models.CharField(choices=status_choices, max_length=11)
    media = models.OneToOneField(Media, on_delete=models.CASCADE)

users/models.py
from django.db import models

# Create your models here.
class UserProfile(models.Model):
    pass

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', "password1", "password2"]

movies/views.py
from urllib import parse
import requests as r
import re, json
import ast

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseForbidden, HttpResponseBadRequest
from django.core import serializers

from .models import Media, Genre, Providers, Torrents

from movies.utilities.scrappers import Scrapper1337x
from movies.utilities.helpers import get1337xSearchUrl
from django.conf import settings



def list_movies(request):
    # TODO: Add cards/list view
    media_filter = request.GET.get('filter', 'all')
    chosen_genre = request.GET.get('genre')
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect('/login')
    media = Media.objects.filter(user=user.pk)
    if chosen_genre:
        # Because of how the genre logic is written media can have duplicated relationships in
        # the M2M table. Using distinct() corrects for this.
        media = media.filter(genre__name=chosen_genre).distinct()
    context = {
        'success': request.GET.get('success', ''),
        'error': request.GET.get('error', ''),
        'media': media,
        'genres': Genre.objects.all(),
        'filter': media_filter,
        'chosen_genre': chosen_genre
    }
    return render(request, 'movies/index.html', context)


def lookup(request):
    # http://www.omdbapi.com#usage
    # Escape all non safe chars.
    title = parse.quote(request.GET.get('title'))
    if re.search(r"^t{2}\d{6,}$", title):
        print("Searching By IMDb ID")
        url = f'http://www.omdbapi.com/?apikey=600f6be7&i={title}'
    else:
        url = f'http://www.omdbapi.com/?apikey=600f6be7&t={title}'
    response = r.get(url).json()
    context = {
        'data': response,
        'search': True
    }
    return render(request, 'movies/index.html', context)


def add(request):
    from .just_watch_api import get_providers
    params = ''
    if request.method == 'POST':
        dict_str = request.body.decode("UTF-8")
        data = ast.literal_eval(dict_str)
    else:
        data = request.GET

    title = data.get('title')
    year = data.get('year')
    runtime = data.get('runtime')
    genre = data.get('genre').split(', ')
    plot = data.get('plot')
    poster = data.get('poster')
    rated = data.get('rated')
    director = data.get('director')
    actors = data.get('actors')
    rating = data.get('rating')
    media_type = data.get('media_type')
    imdbID = data.get('imdbID')
    try:
        media, created = Media.objects.get_or_create(
            imdbID=imdbID,
            defaults={
                'title': title,
                'year': year,
                'runtime': runtime,
                'plot': plot,
                'poster': poster,
                'rated': rated,
                'director': director,
                'actors': actors,
                'rating': rating,
                'media_type': media_type,
                'imdbID': imdbID
            }
        )
        # Get providers
        providers = get_providers(title)
        for item in providers:
            print(f'Adding {item}')
            prov_obj, created = Providers.objects.get_or_create(name=item)
            media.providers.add(prov_obj)
        for g in genre:
            genre_obj, created = Genre.objects.get_or_create(name=g)
            media.genre.add(genre_obj)
        params = f'?success={media_type} added successfully'
    except Exception as e:
        params = f'?error={e}'

    return HttpResponse(status=204)


def add_plex(request):
    movie_id = request.GET.get('movie_id')
    media = Media.objects.filter(imdbID=movie_id)
    media.update(on_plex=True)
    data = {'success': f'Successfully added {movie_id} to plex.'}
    return JsonResponse(data, safe=False)

def list_to_download(request):
    auth_key = request.headers.get("AUTH_KEY")
    
    if auth_key == settings.API_SECRET_KEY:
        torrents = Torrents.objects.filter()
        data = serializers.serialize('json', torrents)
        return HttpResponse(data)
    return HttpResponse('Unauthorized', status=401)

def list_create_1337x_torrents(request):
    media_title = request.GET.get('title')
    search_url = get1337xSearchUrl(media_title)
    torrents = Scrapper1337x(url=search_url).list()
    # TODO: Use serializer
    return JsonResponse(
        torrents, 
        safe=False
    )

def create_torrent_download(request):
    if request.method == 'POST':
        dict_str = request.body.decode("UTF-8")
        data = ast.literal_eval(dict_str)
    else:
        return HttpResponseBadRequest()
    magnet = data.get('magnet')
    media_id = data.get('mediaId')
    print("Magnet:", magnet, "\nMediaId:", media_id)
    if not magnet or not media_id:
        return HttpResponseBadRequest()
    media = Media.objects.get(pk=media_id)
    torrent, wasCreated = Torrents.objects.get_or_create(media=media, defaults={"magnet": magnet, "status": "READY"})
    if wasCreated is False:
        torrent.magnet = magnet
        torrent.save()
        return HttpResponse(status=200)
    return HttpResponse(status=204)

users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm

# Create your views here.
def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
        return redirect('/')
    else:
        form = RegisterForm()

    return render(response, "users/register.html", {"form": form})

movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Movie Watch</title>
    <!-- Compiled and minified CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <!-- Compiled and minified JavaScript -->
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Oswald|Solway&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />

    <style>
      body {
        background-color: black;
        color: white;
        font-family: "Oswald", cursive;
      }
      input {
        color: #5dd6ca;
      }
    </style>
  </head>
  <body>
    <div class="container">{% block content %} {% endblock%}</div>
  </body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script>
    $(document).ready(function () {
      // Init slide
      $(".sidenav").sidenav();
      var side = M.Sidenav.getInstance($(".sidenav"));
      // side.open()
      // init modal
      $(".modal").modal();
      $(".collapsible").collapsible();
    });
  </script>
</html>

movies/templates/movies/includes/cards_display.html
{% load app_extras %}
{% if filter == 'genre' %}
<div class="row genre_sorted">
  <ul>
    {% for genre in genres %}
    <li><h4>{{genre.name}}</h4></li>
    <div class="row">
      {% for item in media %} {% if genre.name|compare_genre:item %}
      <div class="media_item">
        <img src="{{item.poster}}" />
        <p class="card-title">{{item.title}}</p>
      </div>
      {% endif %} {% endfor %}
    </div>
    {% endfor %}
  </ul>
</div>
{% elif filter == 'all' %}
<div style="margin-top: 20px" class="row show_all">
  {% if chosen_genre %}
  <h5>{{chosen_genre}}</h5>
  {% endif %} {% for item in media %}
  <div class="card col s6 m4 l2 black">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="{{item.poster}}" />
    </div>
    <div class="card-content">
      <span class="card-title activator white-text">{{item.title}}</span>
    </div>
    <div class="card-reveal black">
      <p>{{item.title}}</p>
      <span class="card-title white-text text-darken-4 btn-floating btn-small grey darken-4 card-close">
        <i class="material-icons">close</i>
      </span>
      {% for p in item.providers.all %}
      <img src="{{p.logo}}" alt="{{p.name}}" style="height: 40px" />
      {% empty %}
      <label>Not available to stream</label>
      {% endfor %}
      <p>
        <i class="material-icons white-text text-darken-3 left">access_time</i>
        <span style="margin-left: -0.7em">{{item.runtime|toMinutesAndHours}}</span>
      </p>
      <a
        href="#"
        data-target="slide-out"
        class="sidenav-trigger"
        onclick="setupTorrentMenu('{{item.title}}', '{{item.id}}')"
      >
        <i class="material-icons yellow-text text-darken-3">file_download</i>
      </a>
      <a href="#info-modal" onclick="infoModal('{{item.title}}', '{{item.plot}}')">
        <i class="material-icons yellow-text text-darken-3 right bottom">info</i>
      </a>
    </div>
  </div>
  {% endfor %}
</div>
{% endif %}

movies/templates/movies/includes/filters.html
<h6>
    Filter:
    <a href="?filter=all">Show All</a>
    -
    <a href="?filter=genre">By Genre</a>
</h6>
<h6>
    Genres: {% for genre in genres %} {% if forloop.last %}
    <a href="?genre={{genre.name}}">{{genre.name}}</a>
    {% else %}
    <a href="?genre={{genre.name}}">{{genre.name}}</a>
    - {% endif %} {% endfor %}
</h6>

movies/templates/movies/includes/info_modal.html
<div id="info-modal" class="modal blue-grey darken-4">
    <div class="modal-content">
      <h4 id="info-modal-title"></h4>
      <p id="info-modal-plot"></p>
    </div>
    <div class="modal-footer blue-grey darken-4">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat yellow-text text-darken-3">
        Close
      </a>
    </div>
  </div>

movies/templates/movies/includes/search.html
<form action="{% url 'movies:lookup' %}">
    <div class="input-field col s6">
      <input type="text" name="title" class="white-text" />
      <label for="search" class="white-text">Search</label>
    </div>
    <input type="submit" name="submit" class="btn blue" />
</form>

{% if data.Title %}
<div class="row results">
  <div class="col l2 m4 s6">
    <img src="{{data.Poster}}" alt="" />
  </div>
  <div class="col l10">
    <h5>{{data.Title}} | {{data.Year}} | {{data.Runtime}}</h5>
    <h6>{{data.Genre}}</h6>
    <p>{{data.Plot}}</p>
    <form action="{% url 'movies:add' %}">
      {%csrf_token%}
      <!-- Hidden Fields -->
      <input type="hidden" name="title" value="{{data.Title}}" />
      <input type="hidden" name="year" value="{{data.Year}}" />
      <input type="hidden" name="runtime" value="{{data.Runtime}}" />
      <input type="hidden" name="genre" value="{{data.Genre}}" />
      <input type="hidden" name="plot" value="{{data.Plot}}" />
      <input type="hidden" name="poster" value="{{data.Poster}}" />
      <input type="hidden" name="rated" value="{{data.Rated}}" />
      <input type="hidden" name="director" value="{{data.Director}}" />
      <input type="hidden" name="actors" value="{{data.Actors}}" />
      <input type="hidden" name="rating" value="{{data.imdbRating}}" />
      <input type="hidden" name="media_type" value="{{data.Type}}" />
      <input type="hidden" name="imdbID" value="{{data.imdbID}}" />
      <!-- End Hidden -->

      <button class="btn waves-effect waves-light green" type="submit" name="submit">
        Add to List
        <i class="material-icons right">add_box</i>
      </button>
      <a
        href="#"
        data-target="slide-out"
        class="sidenav-trigger btn waves-effect waves-light yellow darken-4"
        onclick="addAndDownload()"
      >
        Add & Download
        <i class="material-icons right">cloud_download</i>
      </a>
    </form>
  </div>
</div>
{% elif search %}
<div class="row results">
  <h5 style="padding: 10px">
    Hmm, I couldnt find that. Make sure its spelt correctly and try, try, try, again.
  </h5>
</div>
{% else %} {% endif %}

movies/templates/movies/includes/sidebar.html
<ul id="slide-out" class="sidenav blue darken-2 text-white">
    <li>
      <div class="user-view">
        <div class="background">
          <img
            src="https://images.squarespace-cdn.com/content/v1/56a16fd5d82d5ee027b1b53f/1536977635987-YQVX0UA7ZAD8ZIYDFGP4/ke17ZwdGBToddI8pDm48kA47qaxzGU3oa60Mv3IrElh7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0hGaawTDWlunVGEFKwsEdnE_ZbuhWuTjDl9Hn0Vaidb23CyzgPgNZ_l0zINYXrCLdg/iStock-817548064+%281%29.jpg?format=750w"
          />
        </div>
        <br />
        <br />
        <span id="" class="white-text title"></span>
      </div>
    </li>
    <!-- Collapsible -->
    <ul class="collapsible">
      <li>
        <div class="collapsible-header" id="1337x-dropdown-trigger">
          <i class="material-icons">filter_drama</i>
          1337x
        </div>
        <div class="collapsible-body blue darken-4">
          <ul class="collection blue darken-4" id="1337x-dropdown"></ul>
        </div>
      </li>
      <li>
        <div class="collapsible-header">
          <i class="material-icons">place</i>
          RARGB
        </div>  
        <div class="collapsible-body blue darken-4"><span>Lorem ipsum dolor sit amet.</span></div>
      </li>
    </ul>
    <li><div class="divider"></div></li>
    <!-- <li><a class="subheader">Subheader</a></li> -->
  </ul>

movies/templates/movies/index.html
{% extends 'movies/base.html' %} {% block content %}
{% include "movies/css/main.css" %}

{% if success or error %}
<span class="msgBox yellow orange-text text-darken-3 darken-1">{{success}}{{error}}</span>
{% endif %}
{% if user.is_authenticated %}
<p class="right">Hello, {{user.username}} <a href="/logout">(logout)</a></p>
{% else %}
<p class="right"><a href="/login">Log in</a></p>
{% endif %}
<h3>Movies</h3>

{% include "movies/includes/search.html" %}

<!-- Filtering -->
{% include "movies/includes/filters.html" %}

<!-- Cards Display -->
{% include "movies/includes/cards_display.html" %}

<!-- Info Modal -->
{% include "movies/includes/info_modal.html" %}

<!-- Side Nav -->
{% include "movies/includes/sidebar.html" %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
  {% include "movies/js/main.js" %}
</script>
{% endblock %}

users/templates/users/login.html
{% extends "movies/base.html" %}

{% block title %}
Login Here
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<form method="POST" class="form-group">
    {% csrf_token %}
    {{form|crispy}}
    <p>Don't have an account? Create one <a href="/register">here</a></p>
    <button type="submit" class="btn btn-success">Login</button>
</form>
{% endblock %}

users/templates/users/register.html
{% extends "movies/base.html" %} {% block title %}Create an Account{% endblock %} {% block content %}
<form method="POST" class="form-group">
  {% load crispy_forms_tags %} {% csrf_token %} {{ form|crispy }}
  <button type="submit" class="btn btn-success">Register</button>
</form>
{% endblock %}